ktor:
  application:
    modules:
      - org.ifs23017.ApplicationKt.module
  deployment:
    port: ${APP_PORT:8080}
    host: ${APP_HOST:0.0.0.0}

  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

  jwt:
    secret: "${JWT_SECRET:dev-secret-change-me}"
